### ISSUE TITLE
Loading the keystore takes a very long time in some rare cases

### ISSUE THREAD

**Issue by nquinquenel** [Hakky54/sslcontext-kickstart#444] opened 2024-01-16 08:38 UTC
Hi, this is more a behavior report than a bug, but it could be valuable to share.

**Describe the bug**

When loading a keystore, it may get stuck on some rare occasions. It can get stuck for 1, 2, 5, 10 minutes, or indefinitely, as reported by the user.

**To Reproduce**

The only reported issue was found on Windows 10. Whenever the user tried to initialize our HTTP client, it got stuck. We retrieved the following stack trace from this user's thread dump:

```
	at platform/jdk.crypto.mscapi@17.0.9/sun.security.mscapi.CKeyStore.loadKeysOrCertificateChains(Native Method)
	at platform/jdk.crypto.mscapi@17.0.9/sun.security.mscapi.CKeyStore.engineLoad(CKeyStore.java:734)
	at platform/jdk.crypto.mscapi@17.0.9/sun.security.mscapi.CKeyStore$MY.engineLoad(CKeyStore.java:60)
	at java.base@17.0.9/java.security.KeyStore.load(KeyStore.java:1473)
	at nl.altindag.ssl.util.KeyStoreUtils.createKeyStore(KeyStoreUtils.java:150)
	at nl.altindag.ssl.util.KeyStoreUtils.createKeyStoreIfAvailable(KeyStoreUtils.java:260)
	at nl.altindag.ssl.util.KeyStoreUtils.lambda$loadSystemKeyStores$1(KeyStoreUtils.java:233)
	at nl.altindag.ssl.util.KeyStoreUtils$$Lambda$1986/0x0000000801397048.apply(Unknown Source)
	at java.base@17.0.9/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@17.0.9/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base@17.0.9/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.9/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.9/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base@17.0.9/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base@17.0.9/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@17.0.9/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at nl.altindag.ssl.util.KeyStoreUtils.loadSystemKeyStores(KeyStoreUtils.java:236)
	at nl.altindag.ssl.util.TrustManagerUtils.createTrustManagerWithSystemTrustedCertificates(TrustManagerUtils.java:89)
	at nl.altindag.ssl.SSLFactory$Builder.withSystemTrustMaterial(SSLFactory.java:209)
```

**Expected behavior**

We would expect the loading of the keystore to take a short time.

**Environmental Data:**
 - Java 17
 - Windows 10
 - Issue happens when using SonarLint (in which we embed the sslcontext-kickstart library) at the IDE startups (when the HTTP client is initialized)

**Additional context**

The issue was fixed by itself, but the user does not know why. Apparently, nothing was changed.

We saw this JDK [bug](https://bugs.openjdk.org/browse/JDK-8313367) report mentioning that, on Windows, it may ask for specific privilege to read the certificates, in which case it could explain the issue the user had. Perhaps it is asking for credentials to read the certificate, and the user might have missed it, or it wasn't proposed at all. So far, this is our only guess.

**Comment by Hakky54** [comment] 2024-01-18 23:26
Hi @nquinquenel 

Thank you for raising this issue. I think this kind of issue should be prevented and no user at all should face a situation where it will get stuck for some amount of time... However I am not sure how to resolve it as there a multiple ways.

If additional priviliges are needed it will raise an exception and it should  get caught + logged, see here: https://github.com/Hakky54/sslcontext-kickstart/blob/master/sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/KeyStoreUtils.java#L268 However I am not sure why it is not happening here and why it hangs for some amount of time. I can reproduce this runtime exception, however I cannot reproduce the case of freezing it. The issue is related probably to Windows-ROOT-LOCALMACHINE and Windows-MY-LOCALMACHINE which I added in the past as a feature request from here https://github.com/Hakky54/sslcontext-kickstart/issues/356

So it might happen that some users are facing this issue and some not. And the issue probably occurs when a specific type of certificate with signing capability is present. Next to that it is not known when the bug report at the openjdk page will be resolved.  However I would prefer to resolve this issue as it might happen that your end-users will face it again in the future while not being able to provide a solution.... 

So I would like to suggest an option which will enable either you or your end-users to disable/exclude windows keystore types if this exceptional situation happens. A different option could be that I built a timeout for fetching system keystores so it will stop attempting after like 500 ms and then move on to the next windows keystore. 

What do you think, would that be a proper solution for you? Which one would be a better one, or do you have a different suggestions?

**Comment by Hakky54** [comment] 2024-01-20 22:42
@nquinquenel I have created a fix which has the two options which I mentioned in my earlier post. It won't wait endless anymore if something is blocking the call. It will just try and wait 200 ms or else it will skip it and try the next one.

I have created a PR here: https://github.com/Hakky54/sslcontext-kickstart/pull/445
Can you maybe have a look at it and share your thougts/give maybe feedback. Looking forward to your reply.

**Comment by Hakky54** [comment] 2024-01-22 09:35
Sure, keep me updated. Looking forward to the updates

**Comment by Hakky54** [comment] 2024-01-23 00:16
I link the jdk bug fix here to keep track of the [jdk bug](https://bugs.openjdk.org/browse/JDK-8313367) you mentioned earlier. Maybe that will also be helpfull to resolve this issue.
https://github.com/openjdk/jdk/pull/16687

**Comment by henryju** [comment] 2024-02-01 14:57
We had another [report](https://community.sonarsource.com/t/sonarlint-triggers-eesp-prompt-on-ide-startup/108397) today: this time this is not a permission issue, but it seems a security software (Entrust EESP) is hooking into the game, and prompt for some credentials before letting us read the certificates.

I think we should provide a way to let users disable this feature (loading OS certificates) on our side. So feel free to close this issue on your side, I am not sure there is a generic way to solve this usability problem.

**Comment by Hakky54** [comment] 2024-02-02 09:43
So it seems like the windows system truststores can cause some trouble to the end-user and it is not limited to just a single end-user. Also it is annoying that they get prompted to provide their password, while it will only read the trusted certificates...

I agree that it makes more sense to have a mechanism on your side so the client can enable/disable this option. I will still investigate whether it can be resolved on the library side. I will keep the issue open for couple of months to further investigate whether it is possible to fix it on the library side

**Closed** 2024-02-23 10:37 UTC
Labels: no-activity

**Comment by Hakky54** [comment] 2024-05-11 21:09
I am linking the OpenJDK bug report here to track the progress for the fix: https://bugs.openjdk.org/browse/JDK-8332076
